// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {handlers} from '../models';

export function AnalyzeMetadata(arg1:handlers.AnalyzeMetadataInput):Promise<handlers.AnalyzeMetadataOutput>;
