// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {handlers} from '../models';

export function DeleteConnection(arg1:handlers.DeleteConnectionInput):Promise<void>;
