// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Disconnect() {
  return window['go']['handlers']['DisconnectHandler']['Disconnect']();
}
