// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ExecuteQuery(arg1) {
  return window['go']['handlers']['ExecuteQueryHandler']['ExecuteQuery'](arg1);
}
