// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {handlers} from '../models';

export function ExecuteQuery(arg1:handlers.ExecuteQueryInput):Promise<handlers.ExecuteQueryOutput>;
