// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GenerateQuery(arg1) {
  return window['go']['handlers']['GenQueryHandler']['GenerateQuery'](arg1);
}
