// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetTableColumns(arg1) {
  return window['go']['handlers']['GetTableColumnsHandler']['GetTableColumns'](arg1);
}
