// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {handlers} from '../models';

export function GetTableColumns(arg1:handlers.GetTableColumnsInput):Promise<handlers.GetTableColumnsOutput>;
